# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  ['push']

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master    
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 12
#     - name: install
#       run: npm install
#     - name: test
#       run: npm run test:
     
  publish:
    if: github.repository == 'roxiness/routify'

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: cycjimmy/semantic-release-action@v2.6.0    
      with:
        semantic_version: 19
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        echo ${{ steps.semantic.outputs.new_release_version }}
        echo ${{ steps.semantic.outputs.new_release_major_version }}
        echo ${{ steps.semantic.outputs.new_release_minor_version }}
        echo ${{ steps.semantic.outputs.new_release_patch_version }}
